insert into public.questions (text, category, big_five_dimension, approved) values
  ('Would you rather explore space or the deep ocean?', 'would-you-rather', 'openness', true),
  ('Mountains or beach? Pick your vibe.', 'preference', 'openness', true),
  ('If you could only eat one cuisine forever, what would it be?', 'hypothetical', 'openness', true),
  ('Do you make plans or wing it?', 'light-personality', 'conscientiousness', true),
  ('Would you rather have a pet dragon or a pet unicorn?', 'would-you-rather', 'openness', true),
  ('Coffee or tea? No wrong answers.', 'preference', 'conscientiousness', true),
  ('If you could live in any fictional world, which would you choose?', 'hypothetical', 'openness', true),
  ('Are you a morning person or a night owl?', 'light-personality', 'conscientiousness', true),
  ('Would you rather have a personal chef or a personal trainer?', 'would-you-rather', 'conscientiousness', true),
  ('Sweet or savory? Breakfast or dessert?', 'preference', 'openness', true),
  ('If you could instantly master any skill, what would it be?', 'hypothetical', 'openness', true),
  ('Do you prefer texting or calling?', 'light-personality', 'extraversion', true),
  ('Would you rather have unlimited sushi or unlimited pizza?', 'would-you-rather', 'openness', true),
  ('City life or countryside? Where’s your happy place?', 'preference', 'openness', true),
  ('If you could time travel, past or future?', 'hypothetical', 'openness', true),
  ('Are you a planner or a last-minute person?', 'light-personality', 'conscientiousness', true),
  ('Would you rather have a personal robot or a personal AI assistant?', 'would-you-rather', 'openness', true),
  ('Sneakers or heels? Comfort or style?', 'preference', 'agreeableness', true),
  ('If you could live in any decade, which would you pick?', 'hypothetical', 'openness', true),
  ('Do you prefer introvert hangouts or big parties?', 'light-personality', 'extraversion', true),
  ('Would you rather have a personal library or a personal art collection?', 'would-you-rather', 'openness', true),
  ('Sweet dreams or action-packed movies?', 'preference', 'openness', true),
  ('If you could instantly learn any language, which would it be?', 'hypothetical', 'openness', true),
  ('Are you more of a rule-follower or a rule-breaker?', 'light-personality', 'conscientiousness', true),
  ('Would you rather have a personal chef or a personal stylist?', 'would-you-rather', 'conscientiousness', true),
  ('Beach vacation or mountain retreat?', 'preference', 'openness', true),
  ('If you could only watch one genre of movies forever, what would it be?', 'hypothetical', 'openness', true),
  ('Do you prefer deep conversations or lighthearted chats?', 'light-personality', 'agreeableness', true),
  ('Would you rather have a personal driver or a personal chef?', 'would-you-rather', 'conscientiousness', true),
  ('Cats or dogs? No judgment here.', 'preference', 'agreeableness', true),
  ('If you could instantly become an expert in anything, what would it be?', 'hypothetical', 'openness', true),
  ('Are you more of a leader or a follower?', 'light-personality', 'extraversion', true),
  ('Would you rather have a personal DJ or a personal masseuse?', 'would-you-rather', 'agreeableness', true),
  ('Summer or winter? Pick your season.', 'preference', 'openness', true),
  ('If you could live in any book, which would you choose?', 'hypothetical', 'openness', true),
  ('Do you prefer spontaneous adventures or planned trips?', 'light-personality', 'conscientiousness', true),
  ('Would you rather have a personal shopper or a personal trainer?', 'would-you-rather', 'conscientiousness', true),
  ('Pizza or tacos? No wrong answers.', 'preference', 'openness', true),
  ('If you could instantly master any sport, what would it be?', 'hypothetical', 'openness', true),
  ('Are you more of a morning person or a night owl?', 'light-personality', 'conscientiousness', true),
  ('Would you rather have a personal chef or a personal stylist?', 'would-you-rather', 'conscientiousness', true),
  ('Ocean or forest? Where’s your happy place?', 'preference', 'openness', true),
  ('If you could only listen to one genre of music forever, what would it be?', 'hypothetical', 'openness', true),
  ('Do you prefer small gatherings or big parties?', 'light-personality', 'extraversion', true),
  ('Would you rather have a personal driver or a personal chef?', 'would-you-rather', 'conscientiousness', true),
  ('Sweet or salty snacks? Pick your poison.', 'preference', 'openness', true),
  ('If you could instantly become fluent in any language, which would it be?', 'hypothetical', 'openness', true),
  ('Are you more of a planner or a go-with-the-flow person?', 'light-personality', 'conscientiousness', true),
  ('Would you rather have a personal masseuse or a personal DJ?', 'would-you-rather', 'agreeableness', true),
  ('City vibes or country life? Where’s your heart?', 'preference', 'openness', true),
  ('If you could live in any movie, which would you choose?', 'hypothetical', 'openness', true),
  ('Do you prefer deep talks or fun banter?', 'light-personality', 'agreeableness', true),
  ('Would you rather have a personal chef or a personal shopper?', 'would-you-rather', 'conscientiousness', true),
  ('Sneakers or boots? Comfort or style?', 'preference', 'agreeableness', true),
  ('If you could instantly master any instrument, what would it be?', 'hypothetical', 'openness', true),
  ('Are you more of a leader or a team player?', 'light-personality', 'extraversion', true),
  ('Would you rather have a personal stylist or a personal trainer?', 'would-you-rather', 'conscientiousness', true),
  ('Sweet dreams or action-packed games?', 'preference', 'openness', true),
  ('If you could live in any video game world, which would you pick?', 'hypothetical', 'openness', true),
  ('Do you prefer texting or face-to-face chats?', 'light-personality', 'extraversion', true),
  ('Would you rather have a personal chef or a personal driver?', 'would-you-rather', 'conscientiousness', true),
  ('Mountains or desert? Pick your adventure.', 'preference', 'openness', true),
  ('If you could instantly become an expert in any field, what would it be?', 'hypothetical', 'openness', true),
  ('Are you more of a rule-follower or a rebel?', 'light-personality', 'conscientiousness', true);